# Generated by Django 5.0.2 on 2024-02-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("name",)},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="name",
        ),
    ]
