# Generated by Django 5.0.2 on 2024-02-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_quantity_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="department",
            field=models.TextField(default=""),
        ),
    ]
