# Generated by Django 5.0.2 on 2024-02-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_order_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.IntegerField(default=0),
        ),
    ]
