# Generated by Django 5.0.2 on 2024-03-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_order_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_cart",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
