# Generated by Django 5.0.2 on 2024-03-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_order_order_cart_order_total_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
    ]
